tasks:
  install-dependencies:
    name: Install dependencies
    command: pip install -e .
    triggeredBy:
      - manual
      - postDevcontainerStart
      - prebuild

services:
  fastapi:
    name: FastAPI
    triggeredBy:
      - manual
      - postEnvironmentStart
    commands:
      start: |
        ona environment port open 8000 --admission creator_only --name FastAPI
        fastapi dev app/main.py --host 0.0.0.0 --port 8000
      ready: curl -fsS http://localhost:8000/
